### ISSUE TITLE
403 Error

### ISSUE THREAD

**Issue by FenyLabs** [nmcardoso/glitch-github-sync#4]
My webhook is giving me a 403 error for some reason. How can I fix this?

**Comment by nmcardoso** [comment]
This error may have been caused by the following part of the code.

https://github.com/nmcardoso/glitch-github-sync/blob/f1bdea9392745cb1eb10722889a10277078c7e1d/server.js#L15-L17

- Check if you have correctly signed the variables GITHUB_URL and GITHUB_SECRET in your project's .env file using the online editor. (see step 3)
- Check if the *Secret* field of the webhook configuration (step 4) has **exactly** the same value as the GITHUB_SECRET variable in the server's .env file (step 3) - white space can cause a different value.
