### ISSUE TITLE
How do we sync it for our own repos? (404 error)

### ISSUE THREAD

**Issue by varunsingh87** [nmcardoso/glitch-github-sync#5]
I get the following error if I use the webhook and .env for my own repository:

<pre>Cannot POST /git</pre>

Do I need to copy your code into my repository somehow? It works if I clone this repository, but for an existing Glitch GitHub repository I am getting the above 404 error.

**Comment by nmcardoso** [comment]
@Borumer Sorry for the delay to answer. You got it?

You can synchronize an existing repository without problems, just put the contents of the server.js file (from this repository) in your project's main `*.js` file, with the exception of the last lines.

Your main file must have the following code:

https://github.com/nmcardoso/glitch-github-sync/blob/f1bdea9392745cb1eb10722889a10277078c7e1d/server.js#L1-L36

Note that the first 7 lines of code may already exist in your main file. 
If the packages were imported under another name, change them to the same name.
If necessary, add these new packages to your `package.json` file, if they are missing

You also need to add the `git.sh` file to your project.

Don't forget to configure the webhook, as described in the `README`
Thus, each commit makes a POST request for the server's route `/git`. 
When this route is requested it synchronizes the github repository with your glitch project. 
That's why the `git.sh` file and some of the functions defined in the `server.js` file are necessary.

**Comment by varunsingh87** [comment]
Thanks, 
I ended up asking a friend who uses Glitch and this repository and he told me what you just told me.

**Comment by nmcardoso** [comment]
Perfect!
